### PR TITLE
Move to actions

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by evaherrada** [comment]
@ladyada Should I add a test.skip for the Metro M4 here?

**Comment by ladyada** [comment]
i just pushed some code to add nrf/m4 support i hope!

**Review by ladyada — APPROVED** [review]

**Comment by evaherrada** [comment]
This is also failing like rgb-lcd-shield was, so I'm reluctant to merge it until that is resolved

**Comment by ladyada** [comment]
libraries that cant push doxy are because arduino-librarians hasnt been given write access
image

**Comment by evaherrada** [comment]
Ah, that makes sense. Thanks for letting me know

**Pull request merged**
